all:	
	cd forward_src; make; cd ..
	cd inversion_src; make; cd ..
	
clean:	
	cd inversion_src; make clean; cd ..
	cd forward_src; make clean; cd ..
	rm tephra2-MAPEweighted tephraMAPEweighted_inversion
